package Bomberman;

public enum Animation {
    PLAYER_IDLE, PLAYER_MOVE_FORWARD, PLAYER_MOVE_BACKWARD, PLAYER_MOVE_LEFT, PLAYER_MOVE_RIGHT, PLAYER_DIE,
    ENEMY_MOVE_FORWARD, ENEMY_MOVE_BACKWARD, ENEMY_MOVE_LEFT, ENEMY_MOVE_RIGHT, ENEMY_DIE,
    BOMB_EXPLODE, EXIT
}
