package Bomberman;

public enum Animation {

    MOVE_EAST,MOVE_WEST,MOVE_NORTH,MOVE_SOUTH,IDLE,DIE,
    APPARITION,CHEST_OPEN,
    EXPLOSION, EXIT,BOMB,IMPACT,
    ITEM_BOMB,HURT,ITEM_RANGE,ITEM_DAMAGE,ITEM_PV,ITEM_KEY,ITEM_SPEED,
    OBSTACLE,BACKGROUND,
    GRASS;

    public final static int DURATION_ANIMATION_ITEM=2000;
    public final static int DURATION_ANIMATION_CHEST=800;
    public final static int DURATION_ANIMATION_EXIT =1500;
    public final static int ANIMATION_EXPLOSION =700;
    public final static int DURATION_ANIMATION_HURT=700;
    public final static int DURATION_ANIMATION_HURT_PLAYER=1000;
}
